### ISSUE TITLE
Case when batch results length is (correctly) less than source length

### ISSUE THREAD

**Issue by nicolasalliaume** [calebmer/graphql-resolve-batch#13]
Hi 👋,
I'm new to GraphQL and ended up here after trying to optimize how the resolver fetches embedded documents (I'm using mongodb+mongoose).

Currently I have the following schema:

```ts
type Query {
        workEntries: [WorkEntry]
        ...
}

type WorkEntry {
        _id: ID!,
        task: Task!,
        ...
}

type Task {
        _id: ID!,
        project: Project!,
        ...
}

type Project {
        name: String!
        ...
}
```

There're 1000+ WorkEntry records, and each linked to a Task, which in turns is linked to a Project.

Now, I'm trying to batch the resolution of tasks since I'd like to avoid one mongodb query per WorkEntry to fetch the Task and then another query to fetch the Project.

I tried adding a resolver for WorkEntry as follows:

```ts
WorkEntry: {
		task: createBatchResolver( workEntries =>
			Task.find( { 
				_id: { 
					$in: workEntries.map( ( { task } ) => task ) 
				} 
			} ).exec()
		)
	},
```

But this is throwing an error saying [it must return the same number of values](https://github.com/calebmer/graphql-resolve-batch/blob/30b7c32c59c40bc0e17ba7a9a1a790b9b312785d/src/batch.js#L125). Now, this would be correct in my case since I have an "N to 1" relationship (multiple WorkEntry documents may be linked to the same task).

Is there any workaround for this? I'm I completely misunderstanding the purpose of this module?

Thanks!

**Comment by calebmer** [comment]
This is actually the correct behavior! You have a list of inputs that look like `['a', 'b', 'c', 'b']` and GraphQL expects to resolve objects in that order. So what you need to do is:

```
createBatchResolver(async workEntries => {
  const tasks = await Task.find(...).exec();
  const taskById = new Map(tasks.map(task => [task._id, task]));
  return workEntries.map(workEntry => taskById.get(workEntry.task));
})
```

**Comment by nicolasalliaume** [comment]
🎉 That worked like charm, thank you @calebmer!

Note to someone looking at this: I needed to use .toString() on ObjectIds so they're equal when adding and getting to/from the Map.
