### ISSUE TITLE
Can this tool play nice with graphql-tools?

### ISSUE THREAD

**Issue by advance512** [calebmer/graphql-resolve-batch#2]
The resolve pattern used by graphql-tools is a bit [different](http://dev.apollodata.com/tools/graphql-tools/resolvers.html).

If so, could you share an example?

**Comment by calebmer** [comment]
Yep, this should work with `graphql-tools` because the resolve function signature is the same! 😊

Please let me know if you experience any problems integrating the two libraries 👍

**Comment by advance512** [comment]
Hey Caleb,

I haven't enough time to get it working. Will try tomorrow.

However, an example in the documentation for graphql-tools usage would go a long way :) It seems to be the "go-to" solution for GraphQL schema implementation nowadays.

**Comment by calebmer** [comment]
It’s definitely a subjective thing. I personally prefer GraphQL.js. I also have a type safe definition library I’m hacking on: https://github.com/calebmer/graphql-strong

More documentation is a good idea though, if you want to submit a PR I’d be happy to merge 😊

**Comment by calebmer** [comment]
I’ve added an example of the batch resolver with `graphql-tools` and a test to make sure that it never regresses:

- https://github.com/calebmer/graphql-resolve-batch/blob/b23b7b2c0efd3667e282dd812ce2ba7813fad52d/examples/graphql-tools.js
- https://github.com/calebmer/graphql-resolve-batch/blob/b23b7b2c0efd3667e282dd812ce2ba7813fad52d/src/batch.test.js#L290

Thanks for your contribution!

**Comment by advance512** [comment]
That is quite awesome! I'll give it a try later this week.
Thanks!
