### ISSUE TITLE
Add example

### ISSUE THREAD

**Issue by sibelius** [calebmer/graphql-resolve-batch#3]
it would be nice to have an example of how to implement this query:

```graphql
{
  users(limit: 5) {
    name
    friends(limit: 5) {
      name
      friends(limit: 5) {
        name
        friends(limit: 5) {
          name
        }
      }
    }
  }
}
```

using this package

**Comment by calebmer** [comment]
Thanks for the suggestion! I’ve added examples that are also now used in the test suite 😊

- https://github.com/calebmer/graphql-resolve-batch/tree/b23b7b2c0efd3667e282dd812ce2ba7813fad52d/examples
- https://github.com/calebmer/graphql-resolve-batch/blob/b23b7b2c0efd3667e282dd812ce2ba7813fad52d/src/batch.test.js#L288-L291

**Comment by sibelius** [comment]
tks for the great work
